### ISSUE TITLE
Chat History to agent

### ISSUE THREAD

**Issue by Santoshbsk** [tdurnford/botframework-human-handoff#1]
Hi.. Is there a way to send all the conversation between the bot and the user to the agent while connecting?

**Comment by EricDahlvang** [comment]
If you are using WebChat with DirectLine, you can use [sendConversationHistory](https://docs.microsoft.com/en-us/javascript/api/botframework-connector/Conversations?view=botbuilder-ts-latest#sendconversationhistory-string--transcript--requestoptionsbase-) api.  It was built for this purpose.

The story for sendConversationHistory not complete right now, which is why we do not have a public sample.  There is an open issue to flush this out here: https://github.com/Microsoft/botbuilder-js/issues/910  

For now, you can check out this repo for a quick example: https://github.com/EricDahlvang/BotBuilder-Samples/tree/eric/node_conversationHistory/samples/javascript_nodejs/22.conversation-history
